### ISSUE TITLE
Unable use ScalNet from Gradle project

### ISSUE THREAD

**Issue by jarutis** [deeplearning4j/ScalNet#17] opened 2016-12-04 14:42 UTC
It seems that it is not possible to set scala.version property like required in ScalNet POM.

If you add `compile 'org.deeplearning4j:scalnet_2.11:0.7.1'` dependancy it throws an error:

```
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not resolve org.deeplearning4j:scalnet_2.11:0.7.0.
  Required by:
      project :
   > Could not resolve org.deeplearning4j:scalnet_2.11:0.7.0.
      > inconsistent module metadata found. Descriptor: org.deeplearning4j:scalnet_!!Specify a Scala version!!:0.7.0 Errors: bad module name: expected='scalnet_2.11' found='scalnet_!!Specify a Scala version!!'
```

As I understand from [this](https://discuss.gradle.org/t/is-it-possible-to-pass-properties-to-pom-xml-as-a-system-property-from-build-gradle/20195) post gradle can't set the required property. Maybe there is some kind of workaround.

**Comment by huitseeker** [comment] 2017-01-16 08:28
This is essentially a duplicate of #15 . It will be fixed through the same method, we'll get to it shortly. Thanks for reporting.

**Closed by huitseeker** 2017-01-16 08:28 UTC
Labels: duplicate
